[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["solady/=lib/solady/src/", "KYCat/=lib/knowyourcat-sdk/src", "@knowyourcat/sdk=lib/knowyourcat-sdk/src/"]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
